'use strict';

// ─── Preguntas de Trivia ─────────────────────────────────────────────────────
// Formato de cada pregunta: [pregunta, respuesta correcta, incorrecta, incorrecta, incorrecta]
// (las opciones se revuelven al jugar). Para agregar preguntas basta con añadir
// líneas a la categoría que quieras.

const CATEGORIES = [
  { id: 'geografia', label: 'Geografía', emoji: '🌎' },
  { id: 'historia', label: 'Historia', emoji: '📜' },
  { id: 'ciencia', label: 'Ciencia', emoji: '🔬' },
  { id: 'deportes', label: 'Deportes', emoji: '⚽' },
  { id: 'cine', label: 'Cine y TV', emoji: '🎬' },
  { id: 'musica', label: 'Música', emoji: '🎵' },
  { id: 'cultura', label: 'Cultura general', emoji: '🧠' },
  { id: 'animales', label: 'Animales', emoji: '🐾' },
  { id: 'comida', label: 'Comida', emoji: '🍔' },
  { id: 'tecnologia', label: 'Tecnología', emoji: '💻' },
  { id: 'banderas', label: 'Banderas', emoji: '🚩' },
  { id: 'emojis', label: 'Películas con emojis', emoji: '🍿' }
];

const QUESTIONS = {
  geografia: [
    ['¿Cuál es la capital de Chile?', 'Santiago', 'Valparaíso', 'Concepción', 'Lima'],
    ['¿Cuál es el río más largo de México?', 'Río Bravo', 'Río Lerma', 'Río Balsas', 'Río Usumacinta'],
    ['¿En qué país está la ciudad de Marrakech?', 'Marruecos', 'Egipto', 'Túnez', 'Argelia'],
    ['¿Cuál es la capital de Venezuela?', 'Caracas', 'Maracaibo', 'Valencia', 'Bogotá'],
    ['¿Qué país tiene más habitantes del mundo?', 'India', 'Estados Unidos', 'Indonesia', 'Rusia'],
    ['¿En qué continente está Australia?', 'Oceanía', 'Asia', 'África', 'Europa'],
    ['¿Cuál es la capital de Canadá?', 'Ottawa', 'Toronto', 'Montreal', 'Vancouver'],
    ['¿Cuál es el río más largo de Sudamérica?', 'Amazonas', 'Paraná', 'Orinoco', 'Magdalena'],
    ['¿Cuál es el país más grande del mundo?', 'Rusia', 'Canadá', 'China', 'Estados Unidos'],
    ['¿Cuál es la capital de Australia?', 'Canberra', 'Sídney', 'Melbourne', 'Perth'],
    ['¿En qué continente está Egipto?', 'África', 'Asia', 'Europa', 'Oceanía'],
    ['¿Cuál es el océano más grande?', 'Pacífico', 'Atlántico', 'Índico', 'Ártico'],
    ['¿Cuál es la montaña más alta del mundo?', 'Everest', 'K2', 'Aconcagua', 'Kilimanjaro'],
    ['¿Cuál es la capital de Japón?', 'Tokio', 'Kioto', 'Osaka', 'Seúl'],
    ['¿Qué país tiene forma de bota?', 'Italia', 'Grecia', 'Portugal', 'Chile'],
    ['¿Cuál es el desierto cálido más grande del mundo?', 'Sahara', 'Atacama', 'Gobi', 'Kalahari'],
    ['¿Cuál es la capital de Perú?', 'Lima', 'Cusco', 'Quito', 'La Paz'],
    ['¿En qué país está la Torre Eiffel?', 'Francia', 'Bélgica', 'Italia', 'Suiza'],
    ['¿Cuál es el país más poblado de América Latina?', 'Brasil', 'México', 'Colombia', 'Argentina'],
    ['¿Cuál es la capital de Colombia?', 'Bogotá', 'Medellín', 'Cali', 'Cartagena'],
    ['¿Qué canal une el océano Atlántico con el Pacífico en Centroamérica?', 'Canal de Panamá', 'Canal de Suez', 'Canal de Kiel', 'Canal de Corinto'],
    ['¿Cuál es la capital de Argentina?', 'Buenos Aires', 'Córdoba', 'Rosario', 'Montevideo'],
    ['¿En qué país está la zona arqueológica de Teotihuacán?', 'México', 'Perú', 'Guatemala', 'Egipto'],
    ['¿Cuál es la capital de Alemania?', 'Berlín', 'Múnich', 'Fráncfort', 'Hamburgo'],
    ['¿Cuál es el país más pequeño del mundo?', 'Ciudad del Vaticano', 'Mónaco', 'San Marino', 'Liechtenstein'],
    ['¿En qué país está Machu Picchu?', 'Perú', 'Bolivia', 'Ecuador', 'Chile'],
    ['¿Cuál es la capital de España?', 'Madrid', 'Barcelona', 'Sevilla', 'Valencia'],
    ['¿Qué cordillera recorre Sudamérica de norte a sur?', 'Los Andes', 'Los Alpes', 'El Himalaya', 'Las Rocosas'],
    ['¿Cuál es la capital de Italia?', 'Roma', 'Milán', 'Venecia', 'Nápoles'],
    ['¿En qué país está la Gran Muralla?', 'China', 'Japón', 'India', 'Mongolia']
  ],
  historia: [
    ['¿Qué imperio construyó la ciudad de Cusco como su capital?', 'El inca', 'El azteca', 'El maya', 'El romano'],
    ['¿Quién fue el primer emperador romano?', 'Augusto', 'Julio César', 'Nerón', 'Calígula'],
    ['¿En qué año se independizó Estados Unidos?', '1776', '1810', '1492', '1789'],
    ['¿Qué civilización inventó la escritura cuneiforme?', 'Los sumerios', 'Los egipcios', 'Los chinos', 'Los griegos'],
    ['¿Quién fue el cura que dio el Grito de Dolores?', 'Miguel Hidalgo', 'José María Morelos', 'Vicente Guerrero', 'Benito Juárez'],
    ['¿Qué muralla se construyó para proteger a China de invasiones?', 'La Gran Muralla', 'El Muro de Adriano', 'El Muro de Berlín', 'La Muralla de Ávila'],
    ['¿En qué año llegó Cristóbal Colón a América?', '1492', '1500', '1512', '1488'],
    ['¿Quién fue el primer presidente de Estados Unidos?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
    ['¿En qué año comenzó la Independencia de México?', '1810', '1821', '1910', '1789'],
    ['¿Qué civilización construyó Machu Picchu?', 'Los incas', 'Los mayas', 'Los aztecas', 'Los olmecas'],
    ['¿En qué año llegó el ser humano a la Luna?', '1969', '1965', '1972', '1958'],
    ['¿Quién pintó la Mona Lisa?', 'Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Pablo Picasso'],
    ['¿En qué año cayó el Muro de Berlín?', '1989', '1991', '1985', '1979'],
    ['¿Qué pueblo fundó la ciudad de Tenochtitlan?', 'Los mexicas (aztecas)', 'Los incas', 'Los mayas', 'Los toltecas'],
    ['¿En qué año terminó la Segunda Guerra Mundial?', '1945', '1939', '1918', '1950'],
    ['¿Quién encabezó la independencia de Venezuela, Colombia, Ecuador, Perú y Bolivia?', 'Simón Bolívar', 'Miguel Hidalgo', 'Benito Juárez', 'José Martí'],
    ['¿Qué barco se hundió en 1912 tras chocar con un iceberg?', 'Titanic', 'Lusitania', 'Britannic', 'Queen Mary'],
    ['¿Qué civilización construyó las pirámides de Guiza?', 'Los egipcios', 'Los romanos', 'Los griegos', 'Los persas'],
    ['¿Quién fue el primer ser humano en pisar la Luna?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'],
    ['¿En qué ciudad está el Coliseo romano?', 'Roma', 'Atenas', 'Florencia', 'Pompeya'],
    ['¿En qué año comenzó la Revolución Mexicana?', '1910', '1810', '1857', '1920'],
    ['¿Qué presidente mexicano dijo "El respeto al derecho ajeno es la paz"?', 'Benito Juárez', 'Porfirio Díaz', 'Lázaro Cárdenas', 'Francisco I. Madero'],
    ['¿En qué año comenzó la Primera Guerra Mundial?', '1914', '1918', '1905', '1939'],
    ['¿Quién fue el primer emperador de los franceses?', 'Napoleón Bonaparte', 'Luis XIV', 'Carlomagno', 'Luis XVI'],
    ['¿Qué país regaló la Estatua de la Libertad a Estados Unidos?', 'Francia', 'Inglaterra', 'España', 'Italia'],
    ['¿Quién fue Cleopatra?', 'Reina de Egipto', 'Emperatriz de Roma', 'Reina de Persia', 'Diosa griega'],
    ['¿Quién fue el primer ser humano en viajar al espacio?', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn', 'Valentina Tereshkova']
  ],
  ciencia: [
    ['¿Cuál es el gas más abundante en el aire que respiramos?', 'Nitrógeno', 'Oxígeno', 'Dióxido de carbono', 'Hidrógeno'],
    ['¿Qué órgano bombea la sangre?', 'El corazón', 'Los pulmones', 'El hígado', 'Los riñones'],
    ['¿Qué planeta está más lejos del Sol?', 'Neptuno', 'Urano', 'Saturno', 'Júpiter'],
    ['¿Cuál es el hueso más largo del cuerpo humano?', 'El fémur', 'La tibia', 'El húmero', 'La columna'],
    ['¿Qué fuerza nos mantiene pegados al suelo?', 'La gravedad', 'El magnetismo', 'La fricción', 'La inercia'],
    ['¿Cuál es el planeta más grande del sistema solar?', 'Júpiter', 'Saturno', 'Neptuno', 'Tierra'],
    ['¿Cuál es el símbolo químico del oro?', 'Au', 'Ag', 'Or', 'Go'],
    ['¿Cuántos huesos tiene el cuerpo humano adulto?', '206', '180', '250', '312'],
    ['¿Qué gas absorben las plantas para hacer la fotosíntesis?', 'Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Hidrógeno'],
    ['¿Cuál es el planeta más cercano al Sol?', 'Mercurio', 'Venus', 'Marte', 'Tierra'],
    ['¿A qué temperatura hierve el agua al nivel del mar?', '100 °C', '90 °C', '120 °C', '80 °C'],
    ['¿Cuál es el órgano más grande del cuerpo humano?', 'La piel', 'El hígado', 'El corazón', 'El cerebro'],
    ['¿Qué científico formuló la teoría de la relatividad?', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    ['¿Cuántos planetas tiene el sistema solar?', '8', '9', '7', '10'],
    ['¿Cuál es la fórmula química del agua?', 'H₂O', 'CO₂', 'O₂', 'H₂O₂'],
    ['¿Qué planeta es conocido como el planeta rojo?', 'Marte', 'Venus', 'Júpiter', 'Mercurio'],
    ['¿Cuál es el animal terrestre más rápido?', 'El guepardo', 'El león', 'El caballo', 'El antílope'],
    ['¿Cuál es el animal más grande del mundo?', 'La ballena azul', 'El elefante africano', 'El tiburón ballena', 'La jirafa'],
    ['¿En qué parte de la célula se encuentra la mayor parte del ADN?', 'El núcleo', 'La membrana', 'El citoplasma', 'La pared celular'],
    ['¿Cuántos corazones tiene un pulpo?', '3', '1', '2', '4'],
    ['¿Qué vitamina produce el cuerpo al tomar el sol?', 'Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina B12'],
    ['¿Qué metal es líquido a temperatura ambiente?', 'Mercurio', 'Plomo', 'Aluminio', 'Estaño'],
    ['¿Quién descubrió la penicilina?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Charles Darwin'],
    ['¿Cuál es la estrella más cercana a la Tierra?', 'El Sol', 'Sirio', 'Alfa Centauri', 'La estrella Polar'],
    ['¿Qué tipo de sangre se considera donante universal?', 'O negativo', 'AB positivo', 'A positivo', 'B negativo'],
    ['¿Qué planeta tiene los anillos más visibles?', 'Saturno', 'Marte', 'Venus', 'Mercurio']
  ],
  deportes: [
    ['¿Cuántos jugadores hay en un equipo de voleibol en la cancha?', '6', '5', '7', '4'],
    ['¿En qué país se inventó el fútbol moderno?', 'Inglaterra', 'Brasil', 'Italia', 'España'],
    ['¿Cuántos hoyos tiene un recorrido normal de golf?', '18', '9', '12', '24'],
    ['Contando el de 2026, ¿qué país ha sido sede del Mundial de fútbol más veces?', 'México', 'Brasil', 'Alemania', 'Argentina'],
    ['¿Cómo se llama el golpe de tenis que se da sin que la pelota bote?', 'Volea', 'Saque', 'Revés', 'Globo'],
    ['¿Cuánto dura un round de boxeo profesional?', '3 minutos', '2 minutos', '5 minutos', '1 minuto'],
    ['¿Cuántos jugadores tiene en la cancha un equipo de fútbol?', '11', '10', '9', '12'],
    ['¿Qué país ha ganado más Copas del Mundo de fútbol?', 'Brasil', 'Alemania', 'Italia', 'Argentina'],
    ['¿Cada cuántos años se celebran los Juegos Olímpicos de verano?', '4', '2', '3', '5'],
    ['¿En qué deporte se usa un disco llamado "puck"?', 'Hockey sobre hielo', 'Curling', 'Polo', 'Lacrosse'],
    ['¿Cuántos puntos vale un triple en baloncesto?', '3', '2', '4', '1'],
    ['¿Qué país fue sede del primer Mundial de fútbol en 1930?', 'Uruguay', 'Brasil', 'Italia', 'Argentina'],
    ['¿En qué deporte destacó Serena Williams?', 'Tenis', 'Atletismo', 'Golf', 'Baloncesto'],
    ['¿Cuántos sets se juegan como máximo en un partido de voleibol?', '5', '3', '4', '7'],
    ['¿Qué selección de fútbol es conocida como "La Albiceleste"?', 'Argentina', 'Uruguay', 'Chile', 'Colombia'],
    ['¿Cuánto mide un maratón?', '42.195 km', '40 km', '21.097 km', '50 km'],
    ['¿En qué deporte se batea un "home run"?', 'Béisbol', 'Críquet', 'Golf', 'Rugby'],
    ['¿Cuántos anillos tiene la bandera olímpica?', '5', '4', '6', '7'],
    ['¿Qué futbolista es apodado "La Pulga"?', 'Lionel Messi', 'Diego Maradona', 'Neymar', 'Luis Suárez'],
    ['¿En qué país se juega el torneo de tenis de Wimbledon?', 'Inglaterra', 'Francia', 'Estados Unidos', 'Australia'],
    ['¿Cuántos jugadores por equipo hay en la cancha en baloncesto?', '5', '6', '7', '4'],
    ['¿En qué deporte ganó Michael Phelps sus medallas olímpicas?', 'Natación', 'Atletismo', 'Ciclismo', 'Remo'],
    ['¿Qué país ganó el Mundial de fútbol 2022?', 'Argentina', 'Francia', 'Croacia', 'Marruecos'],
    ['¿Qué piloto mexicano corrió en Fórmula 1 con Red Bull?', 'Sergio "Checo" Pérez', 'Esteban Gutiérrez', 'Pato O\'Ward', 'Pedro Rodríguez'],
    ['¿Cómo se llama el golpe con el que se empieza cada punto en el tenis?', 'Saque', 'Remate', 'Volea', 'Revés'],
    ['¿Cuántos minutos dura un partido de fútbol sin tiempo extra?', '90', '80', '100', '120'],
    ['¿En qué deporte se usa el término "touchdown"?', 'Fútbol americano', 'Rugby', 'Béisbol', 'Hockey']
  ],
  cine: [
    ['¿Cómo se llama el muñeco de nieve de \"Frozen\"?', 'Olaf', 'Sven', 'Kristoff', 'Hans'],
    ['¿Qué superhéroe usa un escudo con una estrella?', 'Capitán América', 'Iron Man', 'Thor', 'Hulk'],
    ['¿Cómo se llama el perro de los Picapiedra?', 'Dino', 'Scooby', 'Pluto', 'Odie'],
    ['¿En qué película aparece el robot R2-D2?', 'Star Wars', 'Wall-E', 'Terminator', 'Transformers'],
    ['¿Qué héroe de Chespirito usa un "chipote chillón"?', 'El Chapulín Colorado', 'El Chavo del 8', 'El Doctor Chapatín', 'El Chómpiras'],
    ['¿Cómo se llama la casa de magia de Harry Potter?', 'Gryffindor', 'Slytherin', 'Hufflepuff', 'Ravenclaw'],
    ['¿Cómo se llama el vaquero de "Toy Story"?', 'Woody', 'Buzz', 'Rex', 'Andy'],
    ['¿Quién dirigió la película "Titanic" (1997)?', 'James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'],
    ['¿Cómo se llama el ogro verde de DreamWorks?', 'Shrek', 'Fiona', 'Grinch', 'Gru'],
    ['¿Qué actor interpretó a Iron Man en las películas de Marvel?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
    ['¿En qué saga aparece el capitán Jack Sparrow?', 'Piratas del Caribe', 'Hook', 'La isla del tesoro', 'Indiana Jones'],
    ['¿Cómo se llama el papá de Nemo en "Buscando a Nemo"?', 'Marlin', 'Dory', 'Gill', 'Bruce'],
    ['¿Qué serie animada sigue a una familia que vive en Springfield?', 'Los Simpson', 'Padre de familia', 'South Park', 'Futurama'],
    ['¿Qué película de Pixar se ambienta en el Día de Muertos?', 'Coco', 'Encanto', 'Luca', 'Soul'],
    ['¿Qué villano de "Star Wars" dice "Yo soy tu padre"?', 'Darth Vader', 'El Emperador', 'Kylo Ren', 'Boba Fett'],
    ['¿Qué superhéroe es Peter Parker?', 'Spider-Man', 'Batman', 'Superman', 'Flash'],
    ['¿Qué personaje dice "¡Hasta el infinito y más allá!"?', 'Buzz Lightyear', 'Woody', 'Rayo McQueen', 'Wall-E'],
    ['¿Qué personaje de Chespirito vive en un barril?', 'El Chavo del 8', 'Quico', 'El Chapulín Colorado', 'Don Ramón'],
    ['¿Qué película de 1997 ganó 11 premios Óscar?', 'Titanic', 'Avatar', 'Gladiador', 'Jurassic Park'],
    ['¿Cómo se llama la princesa de "Frozen" con poderes de hielo?', 'Elsa', 'Anna', 'Moana', 'Rapunzel'],
    ['¿Qué director mexicano ganó el Óscar con "La forma del agua"?', 'Guillermo del Toro', 'Alfonso Cuarón', 'Alejandro G. Iñárritu', 'Luis Estrada'],
    ['¿Qué ciudad protege Batman?', 'Gotham', 'Metrópolis', 'Springfield', 'Nueva York'],
    ['¿En qué serie aparecen Ross, Rachel y Joey?', 'Friends', 'Seinfeld', 'How I Met Your Mother', 'The Office'],
    ['¿Cómo se llama el protagonista de "El Rey León"?', 'Simba', 'Mufasa', 'Scar', 'Nala'],
    ['¿En qué saga aparecen Frodo y el Anillo Único?', 'El Señor de los Anillos', 'Harry Potter', 'Las crónicas de Narnia', 'Star Wars'],
    ['¿Cómo se llama el mago protagonista de los libros de J. K. Rowling?', 'Harry Potter', 'Merlín', 'Gandalf', 'Doctor Strange']
  ],
  musica: [
    ['¿Qué instrumento toca un baterista?', 'Batería', 'Guitarra', 'Piano', 'Trompeta'],
    ['¿De qué país es el cantante Bad Bunny?', 'Puerto Rico', 'Colombia', 'México', 'República Dominicana'],
    ['¿Qué cantante es conocido como \"El Príncipe de la Canción\"?', 'José José', 'Luis Miguel', 'Juan Gabriel', 'Camilo Sesto'],
    ['¿Cuántas cuerdas tiene un violín?', '4', '5', '6', '3'],
    ['¿Qué género musical es típico de la República Dominicana?', 'Merengue', 'Tango', 'Cumbia', 'Ranchera'],
    ['¿Qué banda grabó el disco \"Abbey Road\"?', 'The Beatles', 'Queen', 'The Rolling Stones', 'ABBA'],
    ['¿Quién es conocido como "El Rey del Pop"?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'],
    ['¿De qué país es la cantante Shakira?', 'Colombia', 'México', 'Venezuela', 'Argentina'],
    ['¿Cuántas cuerdas tiene una guitarra clásica?', '6', '4', '5', '8'],
    ['¿Qué banda británica canta "Bohemian Rhapsody"?', 'Queen', 'The Beatles', 'The Rolling Stones', 'Pink Floyd'],
    ['¿Quién es conocido como "El Rey del Rock and Roll"?', 'Elvis Presley', 'Chuck Berry', 'Michael Jackson', 'Johnny Cash'],
    ['¿De qué ciudad era la banda The Beatles?', 'Liverpool', 'Londres', 'Mánchester', 'Dublín'],
    ['¿Qué cantante es conocido como "El Sol de México"?', 'Luis Miguel', 'Juan Gabriel', 'Vicente Fernández', 'Alejandro Fernández'],
    ['¿Cómo se llama un grupo de cuatro músicos?', 'Cuarteto', 'Trío', 'Quinteto', 'Dúo'],
    ['¿Quién canta "Despacito" junto a Daddy Yankee?', 'Luis Fonsi', 'Bad Bunny', 'Ricky Martin', 'Marc Anthony'],
    ['¿Quién compuso la canción "Amor eterno"?', 'Juan Gabriel', 'José José', 'Joan Sebastian', 'Marco Antonio Solís'],
    ['¿Cuántas notas musicales hay en la escala do, re, mi…?', '7', '5', '8', '12'],
    ['¿Qué cantante es conocida como "La Reina de la Cumbia Tex-Mex"?', 'Selena', 'Thalía', 'Paulina Rubio', 'Gloria Trevi'],
    ['¿Qué género musical tiene a Bob Marley como su gran figura?', 'Reggae', 'Salsa', 'Cumbia', 'Merengue'],
    ['¿Qué instrumento de cuerdas grave es típico del mariachi?', 'Guitarrón', 'Acordeón', 'Gaita', 'Saxofón'],
    ['¿Qué cantante colombiano canta "La camisa negra"?', 'Juanes', 'Carlos Vives', 'Maluma', 'J Balvin'],
    ['¿Qué compositor escribió "Las cuatro estaciones"?', 'Antonio Vivaldi', 'Wolfgang A. Mozart', 'Johann S. Bach', 'Ludwig van Beethoven'],
    ['¿En qué país nació el tango?', 'Argentina', 'Brasil', 'España', 'Cuba'],
    ['¿Qué grupo canta "Dancing Queen"?', 'ABBA', 'Queen', 'Bee Gees', 'Roxette'],
    ['¿Qué cantante es conocido como "El Divo de Juárez"?', 'Juan Gabriel', 'José José', 'Luis Miguel', 'Vicente Fernández'],
    ['¿Qué instrumento tiene teclas blancas y negras?', 'Piano', 'Arpa', 'Violín', 'Trompeta']
  ],
  cultura: [
    ['¿Cuántos días tiene una semana?', '7', '5', '6', '8'],
    ['¿Qué número romano es la \"X\"?', '10', '5', '50', '100'],
    ['¿Cuál es el color de la esperanza según el dicho?', 'Verde', 'Azul', 'Blanco', 'Amarillo'],
    ['¿Quién escribió \"El Principito\"?', 'Antoine de Saint-Exupéry', 'Julio Verne', 'Víctor Hugo', 'Alejandro Dumas'],
    ['¿Cuántos minutos tiene un día?', '1,440', '1,200', '2,400', '720'],
    ['¿Qué se celebra el 25 de diciembre?', 'Navidad', 'Año Nuevo', 'Día de Reyes', 'Día de la Independencia'],
    ['¿Quién escribió "Don Quijote de la Mancha"?', 'Miguel de Cervantes', 'Gabriel García Márquez', 'Lope de Vega', 'Federico García Lorca'],
    ['¿Quién escribió "Cien años de soledad"?', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Octavio Paz', 'Pablo Neruda'],
    ['¿Cuántos días tiene un año bisiesto?', '366', '365', '364', '367'],
    ['¿Cuántos lados tiene un hexágono?', '6', '5', '7', '8'],
    ['¿Qué idioma tiene más hablantes nativos en el mundo?', 'Chino mandarín', 'Inglés', 'Español', 'Hindi'],
    ['¿Qué color se obtiene al mezclar azul y amarillo?', 'Verde', 'Morado', 'Naranja', 'Café'],
    ['¿Cuántos segundos tiene una hora?', '3,600', '600', '6,000', '360'],
    ['¿Cuál es la moneda de Japón?', 'Yen', 'Yuan', 'Won', 'Rupia'],
    ['¿Qué ave es símbolo de la paz?', 'La paloma', 'El águila', 'El búho', 'El cisne'],
    ['¿Qué número romano equivale a 50?', 'L', 'C', 'V', 'D'],
    ['¿En qué país nació la pizza?', 'Italia', 'Grecia', 'Francia', 'Estados Unidos'],
    ['¿Quién pintó "La noche estrellada"?', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí', 'Frida Kahlo'],
    ['¿Qué pintora mexicana es famosa por sus autorretratos con cejas pobladas?', 'Frida Kahlo', 'María Izquierdo', 'Remedios Varo', 'Leonora Carrington'],
    ['¿Cuántas patas tiene una araña?', '8', '6', '10', '4'],
    ['¿Cuál es el ingrediente principal del guacamole?', 'Aguacate', 'Tomate', 'Chile', 'Cebolla'],
    ['¿Qué instrumento sirve para medir la temperatura?', 'Termómetro', 'Barómetro', 'Higrómetro', 'Anemómetro'],
    ['¿Cuál es la moneda de la mayoría de los países de la Unión Europea?', 'Euro', 'Libra', 'Franco', 'Marco'],
    ['¿Cuántos meses del año tienen 31 días?', '7', '6', '5', '8'],
    ['¿En qué idioma se escribieron originalmente los libros de Harry Potter?', 'Inglés', 'Francés', 'Alemán', 'Español'],
    ['¿Qué se celebra en México el 2 de noviembre?', 'Día de Muertos', 'Día de la Independencia', 'Día de la Revolución', 'Día de la Candelaria'],
    ['¿Cuántos jugadores participan en una partida de ajedrez?', '2', '4', '1', '3']
  ],
  animales: [
    ['¿Cuál es el único mamífero que pone huevos además del equidna?', 'El ornitorrinco', 'El canguro', 'El murciélago', 'La ballena'],
    ['¿Qué animal es conocido por cambiar su piel completa al crecer?', 'La serpiente', 'El perro', 'La tortuga', 'El pez'],
    ['¿Cuántas patas tiene un pulpo?', '8', '6', '10', '4'],
    ['¿Qué ave es símbolo de la sabiduría?', 'El búho', 'El loro', 'El águila', 'La paloma'],
    ['¿Dónde guarda el camello su reserva de energía?', 'En la joroba', 'En las patas', 'En la cola', 'En el cuello'],
    ['¿Qué animal es el mejor amigo del hombre según el dicho?', 'El perro', 'El gato', 'El caballo', 'El loro'],
    ['¿Cuál es el animal más alto del mundo?', 'La jirafa', 'El elefante', 'El avestruz', 'El camello'],
    ['¿Qué animal es conocido como "el rey de la selva"?', 'El león', 'El tigre', 'El gorila', 'El jaguar'],
    ['¿Cuántas patas tiene un insecto?', '6', '8', '4', '10'],
    ['¿Cuál de estos mamíferos puede volar?', 'El murciélago', 'El pingüino', 'El canguro', 'El delfín'],
    ['¿Qué tipo de animal es el ajolote?', 'Un anfibio', 'Un pez', 'Un reptil', 'Un mamífero'],
    ['¿Qué ave no puede volar y vive en la Antártida?', 'El pingüino', 'El avestruz', 'La gaviota', 'El albatros'],
    ['¿De qué se alimenta principalmente el panda gigante?', 'Bambú', 'Pescado', 'Frutas', 'Insectos'],
    ['¿Qué animal cambia de color para camuflarse?', 'El camaleón', 'La iguana', 'La tortuga', 'El cocodrilo'],
    ['¿Cuántas jorobas tiene un dromedario?', '1', '2', '3', '0'],
    ['¿Qué insecto produce la miel?', 'La abeja', 'La avispa', 'La hormiga', 'La mariposa'],
    ['¿Qué ave aparece en el escudo de México?', 'El águila', 'El quetzal', 'El colibrí', 'El halcón'],
    ['¿Qué marsupial de Australia se desplaza dando saltos?', 'El canguro', 'El koala', 'El ornitorrinco', 'El wombat'],
    ['¿Qué tipo de animal es la ballena?', 'Mamífero', 'Pez', 'Reptil', 'Anfibio'],
    ['¿Cómo se llama la cría del caballo?', 'Potro', 'Becerro', 'Cordero', 'Lechón'],
    ['¿Qué animal tiene la trompa más larga?', 'El elefante', 'El tapir', 'El oso hormiguero', 'El rinoceronte']
  ],
  comida: [
    ['¿Qué ingrediente lleva siempre la pizza margarita?', 'Albahaca', 'Piña', 'Jamón', 'Champiñones'],
    ['¿De qué país es típico el taco al pastor?', 'México', 'Colombia', 'España', 'Argentina'],
    ['¿Qué antojito mexicano lleva granos de elote con mayonesa, queso y chile?', 'Esquites', 'Pozole', 'Tamales', 'Enchiladas'],
    ['¿Qué bebida se hace con granos tostados y molidos?', 'Café', 'Té', 'Jugo', 'Leche'],
    ['¿Qué país es famoso por el sushi y el ramen?', 'Japón', 'China', 'Tailandia', 'Corea del Sur'],
    ['¿Qué se le pone a las palomitas para que sean dulces?', 'Caramelo', 'Sal', 'Chile', 'Limón'],
    ['¿De qué país es originario el sushi?', 'Japón', 'China', 'Corea del Sur', 'Tailandia'],
    ['¿Cuál es el ingrediente principal del hummus?', 'Garbanzo', 'Lenteja', 'Frijol', 'Haba'],
    ['¿De qué fruta se hace el vino?', 'Uva', 'Manzana', 'Ciruela', 'Cereza'],
    ['¿De qué se hace principalmente el chocolate?', 'Cacao', 'Café', 'Vainilla', 'Caramelo'],
    ['¿Qué país es famoso por la paella?', 'España', 'Italia', 'México', 'Portugal'],
    ['¿Con qué se hace tradicionalmente la tortilla mexicana?', 'Maíz', 'Trigo', 'Arroz', 'Avena'],
    ['¿Qué fruta también se conoce como "ananá"?', 'Piña', 'Papaya', 'Mango', 'Guayaba'],
    ['¿Qué bebida se obtiene del agave azul?', 'Tequila', 'Ron', 'Vodka', 'Pisco'],
    ['¿Qué platillo peruano lleva pescado crudo marinado en limón?', 'Ceviche', 'Lomo saltado', 'Ají de gallina', 'Causa'],
    ['¿Qué pasta tiene forma de tubo cortado en diagonal?', 'Penne', 'Espagueti', 'Fusilli', 'Lasaña'],
    ['¿Qué especia da el color amarillo a la paella tradicional?', 'Azafrán', 'Curry', 'Mostaza', 'Pimienta'],
    ['¿Qué fruta tiene las semillas por fuera?', 'Fresa', 'Kiwi', 'Uva', 'Pera'],
    ['¿De qué animal es la leche del queso manchego?', 'Oveja', 'Vaca', 'Cabra', 'Búfala'],
    ['¿Qué país es famoso por la pizza y la pasta?', 'Italia', 'Francia', 'Grecia', 'Alemania'],
    ['¿Qué grano es la base del arroz con leche?', 'Arroz', 'Avena', 'Trigo', 'Maíz']
  ],
  tecnologia: [
    ['¿Qué significa la \"G\" en las redes 4G y 5G?', 'Generación', 'Gigas', 'Global', 'Gráfica'],
    ['¿Qué empresa creó el buscador más usado del mundo?', 'Google', 'Microsoft', 'Apple', 'Amazon'],
    ['¿Cómo se llama el asistente de voz de Apple?', 'Siri', 'Alexa', 'Cortana', 'Bixby'],
    ['¿Qué tecla se usa para escribir en mayúsculas sostenidas?', 'Bloq Mayús', 'Enter', 'Espacio', 'Tab'],
    ['¿Qué empresa vende la consola Switch?', 'Nintendo', 'Sony', 'Microsoft', 'Sega'],
    ['¿Qué red social es famosa por videos cortos verticales?', 'TikTok', 'LinkedIn', 'Pinterest', 'Wikipedia'],
    ['¿Qué empresa creó el iPhone?', 'Apple', 'Samsung', 'Google', 'Microsoft'],
    ['¿Quién fundó Microsoft junto a Paul Allen?', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'],
    ['¿Qué significan las letras "www" de las páginas web?', 'World Wide Web', 'World Wide Window', 'Web World Wide', 'Wide World Web'],
    ['¿Qué red social creó Mark Zuckerberg?', 'Facebook', 'Twitter', 'TikTok', 'Snapchat'],
    ['¿Cuántos bits tiene un byte?', '8', '4', '16', '10'],
    ['¿Qué empresa desarrolla el sistema Android?', 'Google', 'Apple', 'Microsoft', 'Samsung'],
    ['¿En qué año salió el primer iPhone?', '2007', '2005', '2010', '2003'],
    ['¿Qué empresa fabrica las consolas PlayStation?', 'Sony', 'Nintendo', 'Microsoft', 'Sega'],
    ['¿Cómo se llama el famoso personaje de Nintendo con gorra roja y bigote?', 'Mario', 'Luigi', 'Link', 'Sonic'],
    ['¿Qué app de mensajería tiene un logo verde con un teléfono?', 'WhatsApp', 'Telegram', 'Messenger', 'Signal'],
    ['¿Qué significa la "e" de "e-mail"?', 'Electrónico', 'Enviado', 'Express', 'Externo'],
    ['¿Qué empresa creó Windows?', 'Microsoft', 'Apple', 'IBM', 'Google'],
    ['¿Qué pieza se considera el "cerebro" de la computadora?', 'El procesador', 'La memoria RAM', 'El disco duro', 'La tarjeta de video'],
    ['¿Qué empresa fabrica las consolas Xbox?', 'Microsoft', 'Sony', 'Nintendo', 'Sega'],
    ['¿Qué buscador de internet es el más usado del mundo?', 'Google', 'Bing', 'Yahoo', 'DuckDuckGo']
  ]
};

// 🚩 Banderas: código ISO (imagen en public/flags), nombre y región.
// Las respuestas incorrectas se toman de la misma región para que no sea tan fácil.
const COUNTRIES = [
  // América
  ['mx', 'México', 'am'], ['us', 'Estados Unidos', 'am'], ['ca', 'Canadá', 'am'], ['gt', 'Guatemala', 'am'],
  ['hn', 'Honduras', 'am'], ['sv', 'El Salvador', 'am'], ['ni', 'Nicaragua', 'am'], ['cr', 'Costa Rica', 'am'],
  ['pa', 'Panamá', 'am'], ['cu', 'Cuba', 'am'], ['do', 'República Dominicana', 'am'], ['pr', 'Puerto Rico', 'am'],
  ['jm', 'Jamaica', 'am'], ['ht', 'Haití', 'am'], ['co', 'Colombia', 'am'], ['ve', 'Venezuela', 'am'],
  ['ec', 'Ecuador', 'am'], ['pe', 'Perú', 'am'], ['bo', 'Bolivia', 'am'], ['cl', 'Chile', 'am'],
  ['ar', 'Argentina', 'am'], ['uy', 'Uruguay', 'am'], ['py', 'Paraguay', 'am'], ['br', 'Brasil', 'am'],
  ['bs', 'Bahamas', 'am'], ['tt', 'Trinidad y Tobago', 'am'],
  // Europa
  ['es', 'España', 'eu'], ['pt', 'Portugal', 'eu'], ['fr', 'Francia', 'eu'], ['it', 'Italia', 'eu'],
  ['de', 'Alemania', 'eu'], ['gb', 'Reino Unido', 'eu'], ['ie', 'Irlanda', 'eu'], ['nl', 'Países Bajos', 'eu'],
  ['be', 'Bélgica', 'eu'], ['ch', 'Suiza', 'eu'], ['at', 'Austria', 'eu'], ['se', 'Suecia', 'eu'],
  ['no', 'Noruega', 'eu'], ['dk', 'Dinamarca', 'eu'], ['fi', 'Finlandia', 'eu'], ['is', 'Islandia', 'eu'],
  ['pl', 'Polonia', 'eu'], ['cz', 'República Checa', 'eu'], ['gr', 'Grecia', 'eu'], ['hr', 'Croacia', 'eu'],
  ['ru', 'Rusia', 'eu'], ['ua', 'Ucrania', 'eu'], ['ro', 'Rumania', 'eu'], ['hu', 'Hungría', 'eu'],
  ['tr', 'Turquía', 'eu'], ['rs', 'Serbia', 'eu'], ['bg', 'Bulgaria', 'eu'],
  // Asia
  ['jp', 'Japón', 'as'], ['cn', 'China', 'as'], ['kr', 'Corea del Sur', 'as'], ['kp', 'Corea del Norte', 'as'],
  ['in', 'India', 'as'], ['pk', 'Pakistán', 'as'], ['th', 'Tailandia', 'as'], ['vn', 'Vietnam', 'as'],
  ['ph', 'Filipinas', 'as'], ['id', 'Indonesia', 'as'], ['my', 'Malasia', 'as'], ['sg', 'Singapur', 'as'],
  ['sa', 'Arabia Saudita', 'as'], ['ae', 'Emiratos Árabes Unidos', 'as'], ['il', 'Israel', 'as'], ['ir', 'Irán', 'as'],
  ['iq', 'Irak', 'as'], ['np', 'Nepal', 'as'], ['lk', 'Sri Lanka', 'as'], ['qa', 'Catar', 'as'],
  // África
  ['eg', 'Egipto', 'af'], ['ma', 'Marruecos', 'af'], ['za', 'Sudáfrica', 'af'], ['ng', 'Nigeria', 'af'],
  ['ke', 'Kenia', 'af'], ['et', 'Etiopía', 'af'], ['gh', 'Ghana', 'af'], ['sn', 'Senegal', 'af'],
  ['cm', 'Camerún', 'af'], ['dz', 'Argelia', 'af'], ['tn', 'Túnez', 'af'], ['ci', 'Costa de Marfil', 'af'],
  // Oceanía (se mezcla con Asia para tener suficientes opciones)
  ['au', 'Australia', 'as'], ['nz', 'Nueva Zelanda', 'as'], ['fj', 'Fiyi', 'as']
];

// 🍿 Películas con emojis: [emojis, película]
const EMOJI_MOVIES = [
  ['🦁👑', 'El Rey León'],
  ['❄️👸⛄', 'Frozen'],
  ['🚢🧊💔', 'Titanic'],
  ['🦖🏝️🚙', 'Jurassic Park'],
  ['🕷️🧑🏙️', 'Spider-Man'],
  ['💍🌋🧙‍♂️', 'El Señor de los Anillos'],
  ['⚡👓🧙', 'Harry Potter'],
  ['🐠🔍🌊', 'Buscando a Nemo'],
  ['🤠🚀🧸', 'Toy Story'],
  ['🦈🏊‍♂️🩸', 'Tiburón'],
  ['👻🚫🔫', 'Cazafantasmas'],
  ['🏎️⚡🏁', 'Cars'],
  ['🐀👨‍🍳🍲', 'Ratatouille'],
  ['🎈🏠👴', 'Up'],
  ['🤖🌱🗑️', 'WALL·E'],
  ['💀🎸🌼', 'Coco'],
  ['🧞‍♂️🪔🐒', 'Aladdín'],
  ['🐼🥋🥟', 'Kung Fu Panda'],
  ['👽📞🏠', 'E.T. el extraterrestre'],
  ['🧜‍♀️🐚🦀', 'La Sirenita'],
  ['🌹👸🐃', 'La Bella y la Bestia'],
  ['🍫🏭🎫', 'Charlie y la fábrica de chocolate'],
  ['🚗⏰🔙', 'Volver al futuro'],
  ['👸👠🎃', 'La Cenicienta'],
  ['🍎👸⛏️', 'Blancanieves'],
  ['🐉👦🔥', 'Cómo entrenar a tu dragón'],
  ['🐘👂🎪', 'Dumbo'],
  ['🍝🐕🐕', 'La dama y el vagabundo'],
  ['🟢👹🫅', 'Shrek'],
  ['🦍🏙️✈️', 'King Kong'],
  ['🧪💚👊', 'Hulk'],
  ['🔨⚡👱', 'Thor']
];

module.exports = { CATEGORIES, QUESTIONS, COUNTRIES, EMOJI_MOVIES };
